### ISSUE TITLE
Develop a real style

### ISSUE THREAD

**Issue by tuxsudo** [saltsource/website#1]
Instead of Mr. Salt from Blue's Clues and colors `#bada55`, `#d00d00`, and `#007`, we need something visually aesthetic and pirty.

**Comment by designfrontier** [comment]
Quick color schemes:
https://color.adobe.com/library/7482d493-47cd-4d85-988e-e011a89b2246/theme/16b7683f-c5ff-44b0-9cc1-ecd88727b7df/
https://color.adobe.com/library/7482d493-47cd-4d85-988e-e011a89b2246/theme/16b7683f-c5ff-44b0-9cc1-ecd88727b7df/
https://color.adobe.com/library/674b123c-7edf-4d6c-bf55-942905ed8137/theme/d9d47e0f-2f97-46b7-8f20-054db428d602/
https://color.adobe.com/library/674b123c-7edf-4d6c-bf55-942905ed8137/theme/72109f1f-396c-48d8-af97-5dd10d714eb2/

**Comment by designfrontier** [comment]
For real now...
:one: https://color.adobe.com/saltsource1-color-theme-7656743/
:two: https://color.adobe.com/saltsource4-color-theme-7656755/
:three: https://color.adobe.com/saltsource3-color-theme-7656749/
:four: https://color.adobe.com/saltsource2-color-theme-7656736/

**Comment by tuxsudo** [comment]
Moved to trello...
